version: '3.8'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: instakillogram
    ports:
      - '3306:3306'

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'